server:
  port: 4002
spring:
  application:
    name: Junit
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/junit
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
